[versions]
kotlin = "1.7.20"
ksp = "1.7.20-1.0.6"
redacted-compiler-plugin = "1.2.0"
androidx-navigation = "2.5.2"
hilt = "2.45"
twitter-compose-rules-detekt = "0.0.+"
compose-base = "1.3.1"
compose-compiler = "1.3.2"
